#!/usr/bin/env perl
# Prefix fields of a comma separated line with their index on that line.
# 06/01/2016 - TRCM

# Wot?! no index from zero, shurely shome mishtake!
my $c=1;

@h=split(/,/,(<>));
foreach (@h){
    exit if ($. >= 2);
    printf "%-2d - %s\n",$c,$_;
    $c++;
}
