#!/usr/bin/env perl
# 14/04/2015 - TRCM - Forking with bi-directional parent-child communication

use warnings;
use Socket;
use IO::Handle;


for (my $i=0; $i<5; $i++) {
 socketpair(CHILD, PARENT, AF_UNIX, SOCK_STREAM, PF_UNSPEC) or  die "socketpair: $!"; 
 CHILD->autoflush(1);
 PARENT->autoflush(1);
 
 if ($pid = fork) {
    close PARENT;
    print CHILD "Parent Pid $$ is sending this\n";
    chomp($line = <CHILD>);
    print "Parent Pid $$ just read this: `$line'\n";
    close CHILD;
    waitpid($pid,0);
 } else {
    die "cannot fork: $!" unless defined $pid;
    close CHILD;
    chomp($line = <PARENT>);
    print "Child Pid $$ just read this: `$line'\n";
    print PARENT "Child Pid $$ is sending this\n";
    close PARENT;
    exit;
 } 

}
