#!/usr/bin/perl -CSD
# 2013 - TRCM
# (below not necessary with '-CSD'
#binmode(STDOUT, ":utf8");
use Encode;

my $hex = join('',@ARGV);

if ($hex =~ /:/) {
   $hex =~ s/[: ]//g;
}

print "HEX   - " . join(":",unpack("A*",$hex) =~ m/(..)/g) . "\n";
my $ascii = join("  ",pack("H*",$hex) =~ m/(.)/g);
my $string = join("",pack("H*",$hex) =~ m/(.)/g);
# Print the unprintable as unicode
$ascii =~ tr[\0-\x1F\x7F] [\x{2400}-\x{241F}\x{2421}];
$string =~ tr[\0-\x1F\x7F] [\x{2400}-\x{241F}\x{2421}];
print "ASCII  - " . $ascii . "\n";
# Translate the byte string to UTF-8
my $data = join("",pack("H*",$hex.0x00) =~ m/(..)/g);
print "UTF-8  - ".decode_utf8($data)."\n";
