#!/bin/bash
# Patch the display overrides file to support 1920x1200 HiDPI resolution

### Big Sur...
# System volume now cryptographically sealed, and even in order to do
# this 'csrutil authenticated-root disable', you'd be required to disable
# FileVault, so,... strongly discouraging to do so.
# However,...
# We can just place a copy in /Library and its overlayed!

system_override_base="/System/Library/Displays/Contents/Resources/Overrides"
override_base="/Library/Displays/Contents/Resources/Overrides"

echo -n "Checking ioreg for display key... "
read -r VendorID ProductID <<< "$( \
    ioreg -lw0 | \
        awk -F'-' '/IODisplayPrefsKey/ {
            gsub("\"","");
            print $(NF-1),$(NF)
        }'
    )"
if [[ -z "$VendorID" || -z "$ProductID" ]]; then
    echo "[FAILED]"
    exit 1
else
    echo "[OK]"
fi
echo " + VendorID  : $VendorID"
echo " + ProductID : $ProductID"

override_dir="DisplayVendorID-$VendorID"
override_file="DisplayProductID-$ProductID"

echo -n "Checking for matching override file in the read-only /System ... "
if [[ -f "$system_override_base/$override_dir/$override_file" ]]; then
    echo "[OK]"
    echo " + $system_override_base/$override_dir/$override_file"
else
    echo "[FAILED]"
    exit 1
fi

echo -n "Checking for /Library display override path ... "
if [[ -d "$override_base/$override_dir" ]]; then
    echo "[OK]"
else
    sudo mkdir -p "$override_base/$override_dir"
    echo "[Created]"
fi

echo -n "Checking for 1920x1200 HiDPI override... "
if grep -q 'AAAPAAAACWAAAAAB' "$override_base/$override_dir/$override_file" 2>/dev/null; then
    echo "[ENABLED]"
    exit 0
else
    echo "[NOT PRESENT]"
fi

echo "Creating overlay display override file to enable 1920x1200 HiDPI..."
awk '/<array\>/ {
    $0 = $0 "\n\t\t<data>AAAPAAAACWAAAAAB</data>"
} 1' "$system_override_base/$override_dir/$override_file" 2>/dev/null > "$override_base/$override_dir/$override_file"

echo -n "Verifying 1920x1200 HiDPI override... "
if grep -q 'AAAPAAAACWAAAAAB' "$override_base/$override_dir/$override_file"; then
    echo "[ENABLED]"
    echo " ! Reboot for changes to take effect"
else
    echo "[FAILED!]"
fi
