#!/bin/bash
# Patch the display overrides file to support 1920x1200 HiDPI resolution

override_base='/System/Library/Displays/Contents/Resources/Overrides'

echo -n "Checking ioreg for display key... "
read VendorID ProductID <<< $( \
    ioreg -lw0 | \
        awk -F'-' '/IODisplayPrefsKey/ {
            gsub("\"","");print $(NF-1),$(NF)
        }'
    )
if [[ -z "$VendorID" || -z "$ProductID" ]]; then
    echo "[FAILED]"
    exit 1
else
    echo "[OK]"
fi
echo " + VendorID  : $VendorID"
echo " + ProductID : $ProductID"
override_file="$override_base/DisplayVendorID-$VendorID/DisplayProductID-$ProductID"
override_bkp="$HOME/Desktop/DisplayProductID-$ProductID.backup"

echo -n "Checking for matching override file... "
if [[ -f "$override_file" ]]; then
    echo "[OK]"
else
    echo "[FAILED]"
    exit 1
fi

echo -n "Checking for 1920x1200 HiDPI override... "
if [[ `grep 'AAAPAAAACWAAAAAB' $override_file` ]]; then
    echo "[ENABLED]"
    exit 0
else
    echo "[NOT PRESENT]"
fi

echo -n "Checking status of System Integrity Protection... "
if [[ `csrutil status | grep -i enabled` ]]; then
    echo "[OK]"
else
    echo "[FAILED]"
    echo " ! Cant make changes unless SIP is disabled"
    echo " ! Boot into Recovery Mode, type 'csrutil disable' in Terminal, reboot"
    exit 1
fi

echo -n "Making backup of override file to $override_bkp_$(date +%Y%m%d)... "
cp -f "$override_file" "$override_bkp.$(date +%Y%m%d)"
if [[ -f "$override_bkp.$(date +%Y%m%d)" ]]; then
    echo "[OK]"
else
    echo "[FAILED]"
    exit 1
fi

read -p "OK to to proceed? (Ctrl-C if not) ? "

echo -n "Patching override file to enable 1920x1200 HiDPI..."
awk '/<array\>/ { $0 = $0 "\n\t\t<data>AAAPAAAACWAAAAAB</data>" } 1' $override_bkp > $override_file

echo -n "Verifying 1920x1200 HiDPI override... "
if [[ `grep 'AAAPAAAACWAAAAAB' $override_file` ]]; then
    echo "[ENABLED]"
    echo " ! Boot into Recovery Mode, type 'csrutil enable' in Terminal, reboot"
else
    echo "[FAILED!]"
    echo " ! Please restore $override_bkp to $override_file"
    echo " ! Boot into Recovery Mode, type 'csrutil enable' in Terminal, reboot"
fi
