#!/bin/sh
# Credit to Brad Howes

# You can run this at login by putting the below into
# ~/Library/LaunchAgents/com.user.loginscript.plist
#
#   <?xml version="1.0" encoding="UTF-8"?>
#   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
#   <plist version="1.0">
#   <dict>
#       <key>Label</key>
#       <string>com.user.loginscript</string>
#       <key>ProgramArguments</key>
#       <array>
#           <string>/usr/local/bin/remap_mac_keys</string>
#       </array>
#       <key>RunAtLoad</key>
#       <true/>
#   </dict>
#   </plist>

FROM='"HIDKeyboardModifierMappingSrc"'
TO='"HIDKeyboardModifierMappingDst"'

Map() # FROM TO
{
    CMD="${CMD:+${CMD},}{${FROM}: ${1}, ${TO}: ${2}}"
}

# Referencing :
# https://opensource.apple.com/source/IOHIDFamily/IOHIDFamily-1035.41.2/IOHIDFamily/IOHIDUsageTables.h.auto.html
SECTION="0x700000064"
ESCAPE="0x700000029"
#CAPS_LOCK="0x700000039"
#BACKQUOTE="0x700000035"
#L_SHIFT="0x7000000E1"
#R_COMMAND="0x7000000E7"
#L_CONTROL="0x7000000E0"

if hidutil list | grep -q 'Magic Keyboard with Numeric Keypad'; then
    # Keyboard WITH an escape key, set 'section' key to defaults
    Map ${SECTION} ${SECTION}
elif hidutil list | grep -q 'Touch Bar Display'; then
    # Probably a virtual escape key, remap 'section' to 'esc'
    Map ${SECTION} ${ESCAPE}
fi

#Map ${SHIFT_LOCK} ${L_SHIFT}
#Map ${R_COMMAND} ${SHIFT_LOCK}
#Map ${BACKQUOTE} ${L_CONTROL}

hidutil property --set "{\"UserKeyMapping\":[${CMD}]}"
